model_list:
  - model_name: gpt-5.5
    litellm_params:
      model: deepseek/deepseek-v4
      api_key: os.environ/DEEPSEEK_API_KEY

  - model_name: gpt-5.4
    litellm_params:
      model: deepseek/deepseek-v4-flash
      api_key: os.environ/DEEPSEEK_API_KEY

litellm_settings:
  drop_params: true
